-- session
ALTER SESSION SET CONTAINER=ORCLPDB1;
-- create new user
CREATE USER TEST_USER IDENTIFIED BY test_user;
-- grant priviledes
GRANT CONNECT, RESOURCE, DBA TO TEST_USER;

CREATE TABLE TEST_USER.TEST_USERS (
  ID NUMBER,
  NAME VARCHAR2(50),
  NAME_JA VARCHAR2(100),
  PRIMARY KEY (ID)
);

INSERT ALL
INTO TEST_USER.TEST_USERS VALUES (1, 'TEST_USER', 'テストユーザー')
INTO TEST_USER.TEST_USERS VALUES (2, 'TEST_USER2', 'テストユーザー2')
INTO TEST_USER.TEST_USERS VALUES (3, 'TEST_USER3', 'テストユーザー3')
SELECT * FROM DUAL;